import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('button', { name: 'Explorar Catálogo' }).click();
  await page.getByRole('img', { name: 'A Revolução dos Bichos' }).click();
  await page.getByRole('button', { name: 'Adicionar à Cesta' }).nth(5).click();
  await page.locator('div:nth-child(11) > .card > .card-body > .mt-auto > .d-grid > .btn.btn-primary').click();
  await page.locator('div:nth-child(12) > .card > .card-body > .mt-auto > .d-grid > .btn.btn-outline-info').click();
  await page.getByText('O Alquimista narra a jornada').click(); 
  await page.getByRole('heading', { name: 'Descrição' }).click();
  await page.getByText('O Alquimista Por Paulo Coelho').click();
  await page.getByRole('heading', { name: 'O Alquimista' }).click();
  await page.getByRole('button', { name: 'Adicionar à Cesta' }).click();
  await page.getByRole('link', { name: 'Ver Cesta' }).click();
  await page.getByTitle('Ver detalhes').first().click();
  await page.getByText('256 páginas').click();
  await page.getByRole('link', { name: 'Ver Cesta' }).click();
  await page.getByText('Total de livros:').click();
  await page.getByRole('textbox', { name: 'Observações Gerais' }).click();
  await page.getByRole('textbox', { name: 'Observações Gerais' }).fill('Testes gabs');
  await page.getByText('Renovações: Até 2 vezes').click();
  await page.getByText('Prazo para retirada:').click();
  await page.getByRole('button', { name: 'Finalizar Reservas' }).click();
  await page.getByRole('link', { name: 'Criar Conta' }).click();
  await page.getByRole('textbox', { name: 'Nome Completo *' }).click();
  await page.getByRole('textbox', { name: 'Nome Completo *' }).fill('Gabs QA');
  await page.getByRole('textbox', { name: 'Email *' }).click();
  await page.getByRole('textbox', { name: 'Email *' }).fill('gabs@qa.com.br');
  await page.getByRole('textbox', { name: 'Telefone' }).click();
  await page.getByRole('textbox', { name: 'Telefone' }).fill('(11) 11111-9884');
  await page.getByRole('textbox', { name: 'Telefone' }).click();
  await page.getByRole('textbox', { name: 'Senha *' }).click();
  await page.getByRole('textbox', { name: 'Senha *' }).fill('testesgabs!');
  await page.getByRole('textbox', { name: 'Confirmar Senha *' }).click();
  await page.getByRole('textbox', { name: 'Confirmar Senha *' }).fill('testesgabs!');
  await page.locator('#register-form div').filter({ hasText: 'Li e concordo com os termos' }).click();
  await page.getByRole('button', { name: 'Criar Conta' }).click();
  await page.getByText('Li e concordo com os termos e').click();
  await page.getByRole('button', { name: 'Confirmar Reservas' }).click();
  await page.getByRole('heading', { name: 'Reservas Confirmadas!' }).click();
  await page.getByText('Suas reservas foram criadas').click();
  await page.getByRole('link', { name: 'Ver Minhas Reservas' }).click();
  await page.locator('#recent-activities').getByText('A Revolução dos Bichos').click();
  await page.locator('#recent-activities').getByText('Hub de Leitura').click();
  await page.getByText('O Alquimista').click();
  await page.locator('#total-reservations').click();
  await page.getByRole('link', { name: '  Gabs QA' }).click();
  await page.getByText('Prazo para retirada:').click();
  await page.getByRole('heading', { name: 'Hub de Leitura', exact: true }).click();
});